/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_song_example_jni_FFmpeg */

#ifndef _Included_com_song_example_jni_FFmpeg
#define _Included_com_song_example_jni_FFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_song_example_jni_FFmpeg
 * Method:    openFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_song_example_jni_FFmpeg_play
        (JNIEnv *, jobject, jstring,jobject);

#ifdef __cplusplus
}
#endif
#endif
